### ISSUE TITLE
Split technological progressive and social progressive

### ISSUE THREAD

**Issue by Sizzleboi** [9Axes/9axes.github.io#10]
fearing the robots will take over industries, and being a modern feminist are two completely different things. I agreed with most scientific progress but was extremely traditional on every social issue. These issues are so different that one has bipartisan support while another is a huge focus for the republican party in America.

**Comment by ACCELERATE1488** [comment]
I think the project is dead or something, the author has closed only 3 issues and has not replied to many

**Comment by 9Axes** [comment]
I have taken this feedback into account in the new quiz I have made: https://sixtriangles.github.io/
By moving it into a triangle, there is now one point of the triangle for scientific progress and one for social tradition.
