### ISSUE TITLE
Change the religeon questions to accomodate libertarians

### ISSUE THREAD

**Issue by PhantomDerp** [9Axes/9axes.github.io#13]
You can believe the church helps the poor more than the government because the government is incompetent. Or that the government shouldn't ban religious attire because of freedom of expression. I'm an atheist and I got 60 on the religion axis.

**Comment by 9Axes** [comment]
I have taken this feedback into account in the new quiz I have made: https://sixtriangles.github.io/
These questions have been removed or modified to appropriately make a distinction between tradition, freedom, and progress.
