### ISSUE TITLE
I translated this quiz into Russian

### ISSUE THREAD

**Issue by sikamora** [9Axes/9axes.github.io#18]
[quiz.txt](https://github.com/9Axes/9axes.github.io/files/4808452/quiz.txt)
[questions.txt](https://github.com/9Axes/9axes.github.io/files/4808453/questions.txt)
[instructions.txt](https://github.com/9Axes/9axes.github.io/files/4808454/instructions.txt)
[ru.txt](https://github.com/9Axes/9axes.github.io/files/4808456/ru.txt)
The results: ["Federal - Федералист","Democratic - Демократ","Globalist - Глобалист","Militarist - Милитарист","Security - Сторонник Безопасности","Equality - Сторонник Равенства","Secular - Секулярист","Progressive - Прогрессивист","Assimilationist - Ассимуляционист",Unitary - Унитарист","Authoritarian - Авторитарист","Isolationist - Изоляционист","Pacifist - Пацифист","Freedom Сторонник Свободы","Markets - Сторонник Рынка","Religious - Религиозный","Traditional Традиционалист","Multiculturalist - Мультикультуралист","Fanatic - Фанатичный","Extreme - Радикальный","Moderate - Умеренный","Neutral - Нейтральный"]
result - результат
results - результаты

**Comment by 9Axes** [comment]
I will attempt to add these files as soon as I have time, thank you!

**Comment by 9Axes** [comment]
I have added it here: https://9axes.github.io/ru/
