### ISSUE TITLE
Not everyone who dislikes Democracy is a dictatorship

### ISSUE THREAD

**Issue by RetroHeady** [9Axes/9axes.github.io#3]
The test assumes that anyone that doens't like democracy is a authoritarian, which is just misleading, the anarchist movement despise democracy because of it's flaws and the fact it has a governement evolved, yet they're put into the authoritarian spectrum just because of that.

**Comment by rdococ** [comment]
Left-wing anarchists or right-wing anarchists? You really need to specify, because right-wing anarchists have the annoying habit of pretending that left-wing anarchists don't even exist.

**Comment by kellerw** [comment]
Well, considering that axis is Democracy versus Authoritarianism, labelling them as very Democratic when they despise Democracy is also not accurate. I don't see a good solution to this, the test mostly has the assumption that "Government should exist in some form"

**Comment by Glorken** [comment]
That both "Representatives rarely represent the nation well" and "Elections are an effective way of showing government approval" increase the democracy-axis supports @RetroHeady. Supporting direct democracy and consensus decision-making inherently opposes elections.

This is not to mention that "Popular opinion is not always right" is obviously true, and should not be a question of opinion.

**Comment by 9Axes** [comment]
This is addressed in the new quiz I have made: https://sixtriangles.github.io/
By moving it into a triangle, there is now democracy, authority, and minarchy.
