### ISSUE TITLE
Some criticisms I have

### ISSUE THREAD

**Issue by somemale** [9Axes/9axes.github.io#5]
_conflating scientific progress with social progress_. Some one can believe that we need to spread out through the galaxy and think that women need to stay in the kitchen.

_Conflating multi-multiculturalism with multi-racialism_. Someone who thinks we should have a lot of French immigration is very different than someone who thinks we should have a lot of Mexican immigration. 

I would also add a Patriarchy vs Matriarchy axis if nothing else than to just be clear what tradition you are talking about.

**Comment by 9Axes** [comment]
I have taken this feedback into account in the new quiz I have made: https://sixtriangles.github.io/
By moving it into a triangle, there is now one point of the triangle for scientific progress and one for social progress.
I have also removed the multiculturism axis.
